# .github/workflows/pr-checks.yml
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 libxrandr2 libxss1 libxcursor1 libxcomposite1 libpulse0 libxi6 libxtst6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run ruff
        run: uv run ruff check .
      
      - name: Check imports
        run: |
          uv run python -c "import mindful_touch; print(f'Version: {mindful_touch.__version__}')"
      
      - name: Validate conventional commits
        uses: wagoid/commitlint-github-action@v5
        if: github.event_name == 'pull_request'
        with:
          firstParent: true
          failOnWarnings: false

  test-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Test build process
        run: |
          uv sync
          uv pip install pyinstaller pillow matplotlib
          # Just test spec file generation, not full build
          uv run python -c "
          import sys
          sys.path.insert(0, '.')
          from build_macos import create_spec_file, create_entitlements
          create_spec_file()
          create_entitlements()
          print('✅ Build configuration valid')
          "