# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: mindful-touch
          
          # Version files to update
          extra-files: |
            build_macos.py
            
          # Changelog configuration
          changelog-sections: |
            [
              {"type": "feat", "section": "Features", "hidden": false},
              {"type": "fix", "section": "Bug Fixes", "hidden": false},
              {"type": "perf", "section": "Performance Improvements", "hidden": false},
              {"type": "docs", "section": "Documentation", "hidden": false},
              {"type": "chore", "section": "Maintenance", "hidden": false},
              {"type": "style", "section": "Code Style", "hidden": false},
              {"type": "refactor", "section": "Code Refactoring", "hidden": false},
              {"type": "test", "section": "Tests", "hidden": false},
              {"type": "build", "section": "Build System", "hidden": false},
              {"type": "ci", "section": "Continuous Integration", "hidden": false}
            ]

  # Build and upload macOS app when a release is created
  build-macos:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller pillow matplotlib
      
      - name: Build macOS app
        run: |
          uv run python build_macos.py
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            Mindful Touch-*.dmg
            dist/Mindful Touch.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}