# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: mindful-touch
          
          # Version files to update for Tauri
          extra-files: |
            frontend/src-tauri/Cargo.toml
            frontend/src-tauri/tauri.conf.json
            pyproject.toml
            
          # Changelog configuration
          changelog-sections: |
            [
              {"type": "feat", "section": "Features", "hidden": false},
              {"type": "fix", "section": "Bug Fixes", "hidden": false},
              {"type": "perf", "section": "Performance Improvements", "hidden": false},
              {"type": "docs", "section": "Documentation", "hidden": false},
              {"type": "chore", "section": "Maintenance", "hidden": false},
              {"type": "style", "section": "Code Style", "hidden": false},
              {"type": "refactor", "section": "Code Refactoring", "hidden": false},
              {"type": "test", "section": "Tests", "hidden": false},
              {"type": "build", "section": "Build System", "hidden": false},
              {"type": "ci", "section": "Continuous Integration", "hidden": false}
            ]